# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/EngagementOrganizer.SPA/*
    exclude:
    - pipelines/*

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './src/EngagementOrganizer.SPA/'
 
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: './src/EngagementOrganizer.SPA/'
    customCommand: 'run build -- --prod --base-href ./ --configuration=''production'''
  
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/src/EngagementOrganizer.SPA/dist/'
    artifact: 'ENgagementOrganizer.SPA'
    publishLocation: 'pipeline'