# This is a basic workflow to help you get started with Actions

name: Build Frontend

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build-Frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Angular Build
        run: |
          npm install
          npm run build -- --prod --base-href ./ --outputPath=dist --configuration='production'
        working-directory: ./src/EngagementOrganizer.SPA/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: engagement-organizer-frontend
          path: ./src/EngagementOrganizer.SPA/dist/*
          if-no-files-found: error
          retention-days: 90
