name: Deploy Backend

on:
  workflow_dispatch:
   inputs:
        appservice_suffix:
          description: "AppService Suffix"
          required: true
          default: "DEFAULT"

jobs:
  Deploy-Backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      - name: Download Backend Artifact
        uses: dawidd6/action-download-artifact@v2.11.0
        with:
          workflow: build-backend.yml
          name: engagement-organizer-backend
          branch: master
          path: ./deploy

      - name: Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: deploy/appsettings.json,deploy/appsettings.Development.json,deploy/appsettings.Production.json

      - name: Set env variable
        run: |
          echo ::set-env name=APP_SERVICE_NAME_VARIABLE::APPSERVICENAME_${{github.event.inputs.appservice_suffix }}
          echo ::set-env name=API_KEY_VARIABLE::APPSERVICE_CONFIG_APIKEY_${{ github.event.inputs.appservice_suffix }}

      - name: Deploy Backend
        uses: azure/webapps-deploy@v2
        with:
          app-name:    ${{ secrets[env.APP_SERVICE_NAME_VARIABLE] }}
          package: ./deploy
        env:
          App.ApiKeys: ${{ secrets[env.API_KEY_VARIABLE] }}
          App.DatabasePath: 'EngagementOrganizer.db'

   
